### ISSUE TITLE
documentation/fi4g/dmz/index.md

### ISSUE THREAD

**Issue by samianiba** [fusioninventory/fusioninventory.github.io#80]
this script doesn't work for me, may you explain more for us ?

**Comment by g-bougard** [comment]
Hi @samianiba 
you forgot here to explain what's your purpose. This page is dedicated to inventory in DMZ but what you explained in the [forum](https://forum.fusioninventory.org/showthread.php?tid=10585) is not directly related. Btw as I explained in my forum answer your concern could be served by using the agent HTTP daemon Proxy plugin. I exactly developed this plugin for your kind of problem.

I'm closing this issue here as this is not fully related to the DMZ doc page.
